name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código com permissões para push
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug Git Operations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Test Commit" >> test.txt
          git add test.txt
          git commit -m "test: testing git operations"
          git tag "v0.0.1"
          git push origin main --follow-tags

      # Gerar tag, changelog e atualizar versão no package.json
      - name: Generate version and changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Determinar o tipo de versão com semantic-release
          RELEASE_TYPE=$(npx semantic-release --dry-run | grep -oE 'patch|minor|major' | head -1)

          # Se houver tipo de release válido, atualizar versão e criar changelog
          if [ -n "$RELEASE_TYPE" ]; then
            npx standard-version --release-as $RELEASE_TYPE
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add package.json CHANGELOG.md
            git commit -m "chore(release): update version to $(jq -r .version package.json)"
            git tag "$(jq -r .version package.json)"
            git push origin main --follow-tags
          else
            echo "No release necessary."
          fi
