name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Instalar semantic-release e seus plugins dinamicamente
      - name: Install semantic-release plugins
        run: |
          echo "Installing semantic-release and required plugins..."
          npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git

      # Executar semantic-release para criar versão, changelog, e tag
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running semantic-release to create release..."
          npx semantic-release --no-ci --branches main --plugins \
            "@semantic-release/commit-analyzer" \
            "@semantic-release/release-notes-generator" \
            "@semantic-release/changelog" \
            "@semantic-release/git"

      # (Opcional) Validar a tag criada
      - name: Validate created tag
        run: |
          echo "Checking tags..."
          git fetch --tags
          git tag
