name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout para o repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Instalar dependências globalmente
      - name: Instala dependências
        run: |
          npm install -g semantic-release standard-version @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git

      # Executar semantic-release para criar tag e gerar changelog
      - name: Executa o semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --no-ci --branches main --plugins \
            "@semantic-release/commit-analyzer" \
            "@semantic-release/release-notes-generator" \
            "@semantic-release/changelog" \
            "@semantic-release/git"

      # Atualizar a versão no package.json
      - name: Faz update da versão no package.json
        run: |
          # Obter a versão mais recente do Git
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"

          # Atualizar o package.json com a versão da tag mais recente
          npx standard-version --skip.tag --skip.changelog --release-as $LATEST_TAG

          # Commitar as mudanças no package.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore(release): update package.json to version $LATEST_TAG"
          git push origin main
